spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: test-id
            clientSecret: test_secret
            scope:
              - email
              - profile
  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
jwt:
  issuer: ajufresh@gmail.com
  secret_key: test_key