spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 2491315593-7ct69ppds8ee3d6bvol8b120l7ipdo13.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
jwt:
  issuer: ajufresh@gmail.com
  secret_key: study-springboot